mcurrency_bank_account/models.py
from sqlalchemy import Column, Integer, String, ForeignKey, Float, DateTime, DECIMAL
from sqlalchemy.ext.hybrid import hybrid_method, hybrid_property
from sqlalchemy.orm import relationship, validates
from app import db, login_manager, bcrypt
from datetime import datetime

currency = {
    'USD': 'USD',
    'GBP': 'GBP',
    'EUR': 'EUR',
    'JPY': 'JPY',
    'RUB': 'RUB'
}
# User model

class User(db.Model):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(20), unique=True, index=True, nullable=False)
    _password = Column(String(100))
    banks = relationship('Bank', lazy='joined')

    def __init__(self, username, password):
        self.username = username
        self.password = password

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def password(self, password):
       self._password = bcrypt.generate_password_hash(password, 10)

    @hybrid_method
    def is_correct_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id).encode('utf-8')

    def __repr__(self):
        return '<User %r>' % self.username

@login_manager.user_loader
def user_loader(id):
    return User.query.get(int(id))

# Bank model
class Bank(db.Model):
    __tablename__ = 'banks'
    id = Column(Integer, primary_key=True)
    currency = Column(String(8), nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'))
    user = relationship(User, back_populates='banks')
    amount = Column(DECIMAL(13, 2), nullable=False)
    created_at = Column(DateTime, default=datetime.now())
    updated_at = Column(DateTime, onupdate=datetime.now())

    @validates('currency')
    def validate_currency(self, key, banks):
        assert banks in currency, 'Currency not valid.'
        return banks

    def __init__(self, currency, user_id, user, amount):
        self.currency = currency
        self.user_id = user_id
        self.user = user
        self.amount = amount

    def serializer(self):
        return { 'username': self.user.username, 'currency': self.currency, 'amount': float(self.amount) }

    def __repr__(self):
        return '<Bank %r, %r, %r>' % (self.user_id, self.currency, self.amount)

mcurrency_bank_account/app.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_socketio import SocketIO
from flask_login import LoginManager
from flask_bcrypt import Bcrypt

app = Flask(__name__, instance_relative_config=False)
app.config.from_pyfile('config.py', silent=True)

db = SQLAlchemy(app)
socketio = SocketIO(app, manage_session=True)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
login_manager.login_view = 'auth.login'

# import models, socketio handlers
from models import *
from handlers import *
from controllers import dashboard, auth

app.register_blueprint(dashboard.bp, url_prefix='/')
app.register_blueprint(auth.bp, url_prefix='/auth')

if __name__ == '__main__':
    socketio.run(app, host='0.0.0.0', port=5000, debug=True, use_reloader=True)

mcurrency_bank_account/controllers/auth.py
from flask import Blueprint, g, request, render_template, url_for, flash, redirect
from flask_login import login_user, logout_user, login_required
import models
from app import db

bp = Blueprint('auth', __name__)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('auth/login.html')
    else:
        user = models.User.query.filter_by(username=request.form['username']).first()
        if user is None:
            flash('Invalid username', 'danger')
            return redirect(url_for('auth.login'))

        if not user.is_correct_password(request.form['password']):
            flash('Invalid user password', 'danger')
            return redirect(url_for('auth.login'))

        login_user(user)
        flash('Now you can working with bank account.', 'success')
        return redirect(url_for('dashboard.index'))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('auth/register.html')
    else:
        user = models.User(request.form['username'], request.form['password'])
        db.session.add(user)
        db.session.commit()
        flash('User successfully registered.', 'success')
        return redirect(url_for('auth.login'))

@bp.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('dashboard.index'))

mcurrency_bank_account/controllers/dashboard.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import current_user

import models

bp = Blueprint('dashboard', __name__)

@bp.route('/', methods=['GET'])
def index():
    return render_template('dashboard.html')


@bp.route('/bank/deposit', methods=['GET'])
def deposit():
    return render_template('bank/deposit.html')


@bp.route('/bank/withdraw', methods=['GET'])
def withdraw():
    if len(current_user.banks) == 0:
        flash('Please create first deposit before.','warning')
        return redirect(url_for('dashboard.deposit'))
    bank = current_user.banks[0]
    return render_template('bank/withdraw.html', amount = bank.amount, currency = bank.currency)


@bp.route('/bank/transfer', methods=['GET'])
def transfer():
    return render_template('bank/transfer.html')

mcurrency_bank_account/templates/bank/deposit.html
{% extends "base.html" %}
{% block title %}Multi-currency bank account{% endblock %}
{% block content %}
<div class="content mt-2">
    <form  class="form" onsubmit="return onDepositSubmit(event)">
        <h2 class="text-center title">Deposit</h2>
        <hr />
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                </div>
                <input class="form-control" autofocus placeholder="Amount" type="text" name="amount" />
                <div class="input-group-append ml-2">
                    <select name="currency" class="form-control">
                        <option value="USD" selected>USD</option>
                        <option value="GBP" >GBP</option>
                        <option value="EUR" >EUR</option>
                        <option value="JPY" >JPY</option>
                        <option value="RUB" >RUB</option>
                    </select>
                </div>
            </div>
        </div>
        <!-- <div class="form-group">
            <div class="input-group input-group-sm">
                <select class="form-control">
                    <option value="USD" selected>USD</option>
                    <option value="GBP" >GBP</option>
                    <option value="EUR" >EUR</option>
                    <option value="JPY" >JPY</option>
                    <option value="RUB" >RUB</option>
                </select>
            </div>
        </div> -->
        <div class="form-group text-right">
            <button type="submit" class="btn btn-secondary mr-auto btn-block">Make deposit now</button>
        </div>
    </form>
</div>
{% endblock %}

mcurrency_bank_account/templates/bank/transfer.html
{% extends "base.html" %}
{% block title %}Multi-currency bank account{% endblock %}
{% block content %}
<div class="content mt-2">
    <form action="/auth/login" class="form" method="POST">
        <!-- <h2 class="text-center">Login</h2>
        <hr />
        <div class="form-group">
            <div class="input-group input-group-sm">
                <div class="input-group-prepend">
                    <span class="input-group-text">Username</span>
                </div>
                <input class="form-control" autofocus placeholder="Type here..." type="text" name="username" />
            </div>
        </div>
        <div class="form-group">
            <div class="input-group input-group-sm">
                <div class="input-group-prepend">
                    <span class="input-group-text">Password</span>
                </div>
                <input class="form-control" placeholder="Type here..." type="password" name="password" />
            </div>
        </div>
        <div class="form-group text-center">
            <button type="submit" class="btn btn-primary mr-auto">Login</button>
            or you can <a href="{{url_for('auth.register')}}">Register</a>
        </div> -->
    </form>
</div>
{% endblock %}

mcurrency_bank_account/templates/bank/withdraw.html
{% extends "base.html" %}
{% block title %}Multi-currency bank account{% endblock %}
{% block content %}
<div class="content mt-2">
    <form  class="form form-withdraw" onsubmit="return onWithdrawSubmit(event)">
        <div class="row">
            <div class="col-md-6 text-center">
                <h1>Your balance</h1>
                <hr />
                <h2>{{currency}}</h2>
                <h4 id="my-balance">{{amount}}$</h4>
            </div>
            <div class="col-md-6">
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">$</span>
                            </div>
                            <input class="form-control" autofocus placeholder="Amount" value="{{amount}}" type="text" name="amount" />
                            <div class="input-group-append ml-2">
                                <select name="currency" class="form-control">
                                    <option value="USD" selected>USD</option>
                                    <option value="GBP">GBP</option>
                                    <option value="EUR">EUR</option>
                                    <option value="JPY">JPY</option>
                                    <option value="RUB">RUB</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-secondary mr-auto btn-block">Withdraw</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mcurrency_bank_account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/alertify.js/0.3.11/alertify.default.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">
            MCBA
            <span class="navbar-text">
                multi-currency bank account
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% include "navbar.html" %}
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{category}} alert-dismissible fade show m-3 text-center" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
    {% include "footer.html" ignore missing %}
</body>
</html>

mcurrency_bank_account/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Multi-currency bank account{% endblock %}
{% block content %}
    {% if current_user.is_authenticated %}
        <div class="alert alert-info mt-3 mb-3 text-center" role="alert">
            Welcome to mutli-currency bank account.
                <a href="/bank/deposit" class="btn btn-sm btn-secondary">Deposit</a>

        </div>
    {% else %}
        <div class="alert alert-info mt-3 mb-3 text-center" role="alert">
            Welcome to mutli-currency bank account.
            <a href="/auth/login">Login</a> / <a href="/auth/register">Register</a>
        </div>
    {% endif %}
{% endblock %}

mcurrency_bank_account/templates/footer.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/alertify.js/0.3.11/alertify.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{{url_for('static', filename='notify.min.js')}}"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.slim.js"></script>

<script src="{{url_for('static', filename='app.js')}}"></script>
<footer class="footer">
    &copy;2018
</footer>

mcurrency_bank_account/templates/navbar.html
<ul class="navbar-nav ml-auto">
    {% if current_user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link amount" href="/bank/deposit"><span id="amount">0.00</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/">Dashboard</a>
    </li>
    <!-- <li class="nav-item">
        <a class="nav-link" href="/deposit">Deposit</a>
    </li> -->
    <li class="nav-item">
        <a class="nav-link" href="/bank/withdraw">Withdraw</a>
    </li>
    <!-- <li class="nav-item">
        <a class="nav-link" href="/transfer">Transfer</a>
    </li> -->
    <li class="nav-item">
        <a class="nav-link" href="/bank/transfer">Transfer</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/auth/logout">logout</a>
    </li>
    {% endif %}
    {% if not current_user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link" href="/auth/register">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/auth/login">Login</a>
    </li>
    {% endif %}
</ul>